version: 2

sources:
  - name: raw
    description: Raw data layer containing source tables
    database: DATA_ENGINEERING_DB
    schema: RAW
    tables:
      - name: raw_tsla_stock
        description: Raw Tesla (TSLA) stock price data from 2012-2022
        columns:
          - name: date
            description: Trading date
            tests:
              - not_null
              - unique
          - name: open
            description: Opening price
          - name: high
            description: Highest price of the day
          - name: low
            description: Lowest price of the day
          - name: close
            description: Closing price
            tests:
              - not_null
          - name: adj_close
            description: Adjusted closing price
          - name: volume
            description: Trading volume
            tests:
              - not_null
          - name: _loaded_at
            description: Timestamp when data was loaded
